In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

## What is an array?
An array is a data structure that stores a collection of elements of the same data type at contiguous memory locations. Each element in the array is identified by at least one array index or key, and the position of each element can be computed from its index by a mathematical formula. Arrays are used in programming to store a large amount of data of a similar type and allow easy access to and manipulation of the elements. In some programming languages, the size of an array is fixed once it is declared, meaning it cannot be changed during the program's execution. Arrays are widely used in computer science and are among the oldest and most important data structures, being used by almost every program


In [5]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [6]:
a2 = a[np.newaxis,  :]
print(a2)
a2.shape

[[0 1 2 3 4 5]]


(1, 6)

In [7]:
a3 = a2[np.newaxis, :]
print(a3)
a3.shape

[[[0 1 2 3 4 5]]]


(1, 1, 6)

## Creating Arrays with Numpy

In [8]:
a = np.array([1,2,3,4,5,6,7])
b = np.array([(1,2,3,4,5,6,7),(4,5,6,7,8,9,10)])

In [9]:
a.shape

(7,)

In [10]:
b.shape

(2, 7)

In [11]:
print(a)

[1 2 3 4 5 6 7]


In [12]:
print(b)

[[ 1  2  3  4  5  6  7]
 [ 4  5  6  7  8  9 10]]


In [13]:
# initialize array
zeros = np.zeros((3,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
ones = np.ones((3,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
full = np.full((3,4), 7)
full

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [16]:
identity = np.eye(5)
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
full.dtype

dtype('int32')

In [18]:
identity.dtype

dtype('float64')

In [19]:
type(a)

numpy.ndarray

In [20]:
len(a)

7

In [21]:
a.ndim

1

In [22]:
a.size

7

In [23]:
# Operations
g = a-b
g

array([[ 0,  0,  0,  0,  0,  0,  0],
       [-3, -3, -3, -3, -3, -3, -3]])

In [25]:
h = a+b
h

array([[ 2,  4,  6,  8, 10, 12, 14],
       [ 5,  7,  9, 11, 13, 15, 17]])

In [26]:
h1 = np.add(a,b)
h1

array([[ 2,  4,  6,  8, 10, 12, 14],
       [ 5,  7,  9, 11, 13, 15, 17]])

In [28]:
#multiply
j = a/b
j

array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        ],
       [0.25      , 0.4       , 0.5       , 0.57142857, 0.625     ,
        0.66666667, 0.7       ]])

In [29]:
k = a**2
k

array([ 1,  4,  9, 16, 25, 36, 49])